// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type User struct {
	UserID         string
	MembershipType int64
	AccessToken    string
	RefreshToken   string
	TokenExpiry    time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
